### ISSUE TITLE
test project role has propagated as part of reconcile

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [wharfie/wharfie#83]
There are issues with backfill/migrations having to do some retries while the project role propagates

InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    at throwDefaultError (/wharfie/node_modules/@smithy/smithy-client/dist-cjs/index.js:844:20)
    at throwDefaultError (/wharfie/node_modules/@smithy/smithy-client/dist-cjs/index.js:853:5)
    at de_CommandError (/wharfie/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4751:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async <anonymous> (/wharfie/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20)
    at async <anonymous> (/wharfie/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18)
    at async <anonymous> (/wharfie/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38)
    at async <anonymous> (/wharfie/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:174:18)
    at async <anonymous> (/wharfie/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22)
    at async <anonymous> (/wharfie/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22)
    at async cv.getObject (/wharfie/lambdas/lib/s3.js:89:20)
    at async O1.followSymlinks (/wharfie/lambdas/operations/actions/lib/partition.js:54:20)
    at async O1.followTableSymlink (/wharfie/lambdas/operations/actions/lib/partition.js:88:41)
    at async Object.run (/wharfie/lambdas/operations/actions/register_missing_partitions.js:40:5)
    at async Object.route (/wharfie/lambdas/operations/backfill/index.js:126:14)

**Comment by Ramshackle-Jamathon** [comment]
Superseded by #126, which preserves provider identity readiness and bounded reconciliation in Wharfie's current capability model. The v1 project-role path described here was removed by #125, so further work should be tracked on #126.
