### ISSUE TITLE
Refresh credentials on UnrecognizedClientException

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [wharfie/wharfie#84]
Credentials might change and become invalidate and the lambdas need to refresh them when that happens

daemon caught error UnrecognizedClientException: The security token included in the request is invalid.
    at throwDefaultError (/wharfie/node_modules/@smithy/smithy-client/dist-cjs/index.js:844:20)
    at throwDefaultError (/wharfie/node_modules/@smithy/smithy-client/dist-cjs/index.js:853:5)
    at de_CommandError (/wharfie/node_modules/@aws-sdk/client-glue/dist-cjs/index.js:6396:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async <anonymous> (/wharfie/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20)
    at async <anonymous> (/wharfie/node_modules/@smithy/core/dist-es/middleware-http-signing/httpSigningMiddleware.js:18:20)
    at async <anonymous> (/wharfie/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38)
    at async <anonymous> (/wharfie/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22)
    at async JI.getTable (/wharfie/lambdas/lib/glue.js:226:12)
    at async k1.getCalculatePartitionQueries (/wharfie/lambdas/operations/actions/lib/compaction.js:233:23)
    at async Object.run (/wharfie/lambdas/operations/actions/find_compaction_partitions.js:43:24)
    at async Object.route (/wharfie/lambdas/operations/backfill/index.js:128:14)
    at async daemonRouter (/wharfie/lambdas/daemon.js:68:14)
    at async daemon (/wharfie/lambdas/daemon.js:127:25)
    at async processRecord (/wharfie/lambdas/daemon.js:325:7), retrying Record:

**Comment by Ramshackle-Jamathon** [comment]
Superseded by #126, which preserves refreshable runtime identity in Wharfie's current capability model with explicit acceptance criteria. The v1 Lambda/Glue path described here was removed by #125, so further work should be tracked on #126.
